version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo DATABASE_HOST=${DATABASE_HOST} >> .env
      - echo DATABASE_USER=${DATABASE_USER} >> .env
      - echo DATABASE_PASS=${DATABASE_PASS} >> .env
      - echo DATABASE_NAME=${DATABASE_NAME} >> .env
      - echo DATABASE_PORT=${DATABASE_PORT} >> .env
      - echo SECRET_KEY=${SECRET_KEY} >> .env
      - echo DEBUG=${DEBUG} >> .env
      - echo DATABASE=${DATABASE} >> .env
      - echo ALLOWED_HOSTS=${ALLOWED_HOSTS} >> .env
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose push
      - echo Writing image definitions file...
      - printf '{"AWSEBDockerrunVersion":"1","Image":{"Name":"%s","Update":"true"},"Ports":[{"ContainerPort":8000,"HostPort":80}]}' ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/asbx-org:latest > Dockerrun.aws.json
      - cat Dockerrun.aws.json
      - cat .env
artifacts:
  files: Dockerrun.aws.json