version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username $AWS_ACCOUNT_NAME --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - printenv > .env
      - echo DEBUG=0 >> .env
      - echo ALLOWED_HOSTS=devasbxapp-env.eba-b9kv8mba.us-west-2.elasticbeanstalk.com >> .env
      - docker-compose build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose push
      - echo Writing image definitions file...
      - printf '{"AWSEBDockerrunVersion":"1","Image":{"Name":"%s","Update":"true"},"Ports":[{"ContainerPort":8000,"HostPort":80}]}' ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/asbx-org:latest > Dockerrun.aws.json
      - cat Dockerrun.aws.json
      - cat .env
artifacts:
  files: Dockerrun.aws.json