version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - printenv > web/.env
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose push
      - echo Writing image definitions file...
      - printf '{"AWSEBDockerrunVersion":3,"containerDefinitions":[{"name":"web","image":"%s","hostname":"web","memory":2048,"essential":true,"portMappings":[{"hostPort":8000,"containerPort":8000}]},' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/asbx-org > Dockerrun.aws.json
      - printf '{"name":"nginx","image":"%s","hostname":"nginx","memory":512,"essential":true,"portMappings":[{"hostPort":80,"containerPort":80}],"links":["web"]}]}' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/app-nginx >> Dockerrun.aws.json
      - cat Dockerrun.aws.json
artifacts:
  files: Dockerrun.aws.json