version: '3'
services:
  web:
    build:
      context: ./web
    container_name: web
    image: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/asbx-org'
    volumes:
      - static_volume:/web/staticfiles
      - media_volume:/web/mediafiles
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-nginx'
    volumes:
      - static_volume:/web/staticfiles
      - media_volume:/web/mediafiles
    ports:
      - "80:8000"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
