version: '3'
services:
 web:
  build:
   context: ./
  container_name: asbx-org
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/asbx-org
  environment:
   ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  ports:
   - "8000:80"
   - "443:443"