version: '3'
services:
  web:
    build:
      context: ./web
    container_name: asbx-org
    image: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/asbx-org'
    ports:
      - '8000:8000'
      - '443:443'
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-nginx'
    ports:
      - '80:80'
    depends_on:
      - web