
   version: '3'
   # Defining the compose version
   services:
    # Nginx server
    nginx:
     # Build context
     build:
      context: ./nginx
     container_name: nginx
     image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/nginx
     # Mapping machine and container ports
     ports:
      - "80:80"
     depends_on:
      - web
     restart: "on-failure"

    # Django application
    web:
     # Build context
     build:
      context: ./web
     container_name: asbx-org
     image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/asbx-org
     # Build commands
     command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py createsuperuser_if_none_exists &&
      gunicorn MovieApp.wsgi:application --bind 0.0.0.0:8000"

     # Exposing port 8000
     ports:
      - "8000:8000"
      - "443:443"
     restart: "on-failure"