version: '3'
services:
 web:
  build:
   context: ./
  container_name: asbx-org
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/asbx-org
  environment:
   DATABASE_HOST: ${DATABASE_HOST}
   DATABASE_USER: ${DATABASE_USER}
   DATABASE_PASS: ${DATABASE_PASS}
   DATABASE_NAME: ${DATABASE_NAME}
   DATABASE_PORT: ${DATABASE_PORT}
   SECRET_KEY: ${SECRET_KEY}
   DEBUG: ${DEBUG}
   DATABASE: ${DATABASE}
   ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  ports:
   - "8000:80"
   - "443:443"