# Generated by Django 4.1 on 2022-09-01 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cover', models.ImageField(upload_to='cover/%Y/%m/%d')),
                ('movie', models.FileField(upload_to='Movies/%Y/%m/%d')),
                ('art', models.ImageField(upload_to='art/%Y/%m/%d')),
                ('actors', models.ManyToManyField(to='moviesite.actors')),
                ('category', models.ManyToManyField(to='moviesite.categories')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moviesite.countries')),
                ('film_director', models.ManyToManyField(to='moviesite.filmdirectors')),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='placeholder.png', upload_to='avatar/%Y/%m/%d')),
                ('user_name', models.CharField(max_length=255)),
                ('favorite', models.ManyToManyField(to='moviesite.movie')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=8)),
                ('like', models.IntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('rating', models.FloatField(default=0)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='moviesite.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moviesite.years'),
        ),
    ]
