# Generated by Django 4.0.6 on 2022-09-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0002_userprofile_email_alter_userprofile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
